format_version: 3
pipelines:
  "sample":
    group: default
        label_template: "${COUNT}"
        lock_behaviour: none
        materials:
          git:
            git: git@github.com:RiyaCheriyan/hello-world.git	
        stages:
         - build: 
            clean_workspace: true
            jobs:
              defaultJob:
                timeout: 0
                tasks:	          
                    - exec:
                       command: bash
                       runif: passed
