format_version: 3
pipelines:
  "Sample":
     group:
        label_template: "${COUNT}"
        lock_behaviour: none
     materials:
          mygit:
           git: git@github.com:RiyaCheriyan/hello-world.git
     stages:
        - build: 
            clean_workspace: true
            jobs:
              defaultJob:
                tasks:
                - exec:
                     command: make                     
