format_version: 5
pipelines:
  Sample:
    group: demo
	label_template: ${COUNT}
	lock_behaviour: none
	materials:
          git:
           git: git@github.com:RiyaCheriyan/hello-world.git
        stages:
         - build:
            clean_workspace: true
            jobs:
		defaultjob:
		  timeout: 0
     		  tasks:
                    - exec:
                       command: bash
                       runif: passed
